### ISSUE TITLE
Nothing appearing in site map editor

### ISSUE THREAD

**Issue by lillyfisher** [davidyack/CRMSiteMapEditor#21]
I am trying to rearrange the site map using the site map editor tool, but there are no ribbons/buttons/etc appearing on the scree.

**Comment by davidyack** [comment]
We have been having some problems with the tool working with some  CRM organizations.  We’ve had a support ticket open with Microsoft for the last couple of weeks and have been pushing to escalate it.   The issue doesn’t appears to be all related to the Microsoft service, so different browsers etc. don’t seem to make a difference.  What we have seen is that some CRM organizations work and then stop working, and then start working again.  I hope to hear more from Microsoft today with an update, but so far they have not been able to provide any workarounds - stay tuned we hope to have it resolved ASAP.

**Comment by lillyfisher** [comment]
Thank you for your response, David. I'll keep checking in on the tool with
my fingers crossed! The tool was extremely helpful when it was working, so
I hope it'll be running again soon!

On Tue, Jan 12, 2016 at 1:52 PM, David Yack notifications@github.com
wrote:

> We have been having some problems with the tool working with some CRM
> organizations. We’ve had a support ticket open with Microsoft for the last
> couple of weeks and have been pushing to escalate it. The issue doesn’t
> appears to be all related to the Microsoft service, so different browsers
> etc. don’t seem to make a difference. What we have seen is that some CRM
> organizations work and then stop working, and then start working again. I
> hope to hear more from Microsoft today with an update, but so far they have
> not been able to provide any workarounds - stay tuned we hope to have it
> resolved ASAP.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/davidyack/CRMSiteMapEditor/issues/21#issuecomment-171012379
> .

## 

[image: IntrapriseLogo_small]

Lilly Fisher

Business Analyst

(816) 886-8854

To the extent that information in and/or attached to this email contains
confidential or proprietary information of Intraprise Solutions, Inc.
(“ISI”) or constitutes or contains “nonpublic personal information” as
defined under 16 C.F.R. 313.3(n) pursuant to the Graham Leach Bliley Act,
it is strictly privileged, confidential and private and intended to be
disclosed to and utilized solely by authorized employees, officers,
affiliates and agents of ISI with a need to know such information.  Please
be advised that any unauthorized dissemination, use, disclosure, copying,
distribution, or the taking of any action in reliance on the contents of
this information is strictly prohibited and may be subject to civil and
criminal penalties.  If you are not authorized to receive this information,
you have received this email in error or you are not the intended
recipient, please immediately notify the sender via telephone or return
email, destroy and delete the email and its attachments and refrain from
reviewing, using, copying, sending or disclosing the email or its
attachments.

**Comment by davidyack** [comment]
Yesterday we published a work around for this and we believe this issue is now resolved
